package components

import models.Piece
import play.api.Play.current
import play.api.db.slick.DB
import play.api.db.slick.Session
import scala.slick.jdbc.StaticQuery
import scala.slick.jdbc.SQLInterpolation
import scala.util.Try
import java.net.URL

/**
 * @author juri
 */
trait PieceComponent {

  def initComponent(cake: ActiveSlickCake = ActiveSlickCake.cake) = new PieceComponent(cake)

  lazy val dal = initComponent()

  class PieceComponent(val cake: ActiveSlickCake) {
    
    def processURL(str: String): String = 
      Try(new URL(str)).getOrElse(new URL("/assests/title-cover.png")).toString()
      
    def draftPiece(authorId: Long) = Piece.flattenedPiece(
      None, //id --> to be generated by active record 
      "Title goes here",
      "Short summary",
      processURL(""),
      None, //draft 
      authorId,
      Set("tag1", "tag2"),
      0.0, //rating 
      "markdown source")

    //TODO
    def isOwner(pieceId: Long, userId: Long) = true

    def findByPieceId(id: Option[Long])(implicit author_id: Long): Piece = {
      id match {
        case Some(id) =>
          DB.withSession {
            implicit session: Session =>
              cake.Pieces.findById(id)
          }
        case None => draftPiece(author_id)  
      }

    }
  }
}